### PR TITLE
added an ELB for the PES module

### PR DESCRIPTION
**Pull request by rberlind**
I added an ELB for the PES module since one is needed in front of the primary and standby PTFE servers in the Production External Services deployment option.  I did not try to configure it to only point to the primary PTFE server.  But I figured this would be a good start and that after people deploy it, they could fine tune it.

### CODE REVIEW

**Comment by rberlind** [comment]
I also added in an ssl_certificate_id variable which is needed by the new ELB.

**Comment by rberlind** [comment]
While making improvements, I also decided to change the top level output to be called "PosgreSQL Password" instead of "replicated console password" which was incorrect.  The generated password is NOT used for securing the Replicated admin console.  The user still has to provide that themselves.  Instead, it is used as the password for the RDS PostgreSQL database if external services are configured.

**Comment by rberlind** [comment]
I also added a route53_zone variable and set default to "hashidemos.io" so that this value is not hard coded in the aws_route53_zone.hashidemos data source in top-level main.tf.

**Comment by rberlind** [comment]
Let's hold off on merging this.  I might replace the ELB with an ALB which might avoid need for SSL certificate.

**Comment by rberlind** [comment]
Actually, I think the ELB is fine.  Also, I've determined that the SSL certificate needed by the ELB is placed on the ELB itself and is not the certificate of the PTFE instance.  And I was able to make my ELB load balance against my PTFE instance that used a self signed cert.  I am seeing the Not Secure warning in Chrome and https crossed out and red, but that is probably to be expected with a self-signed PTFE cert.

So, if anyone is able to review and merge my various changes, that would be great.

**Comment by mofesola** [comment]
I was actually thinking of pushing something like this. In addition, it will be great if we could have a provisioner that pushes the licence file as a part of the instance's initialization, add a data module to pull the respective AMI from the region you're working from automatically instead of hardcoding that. Also maybe the possibility of using an ALB in front should be optional (I would use an ALB, anyway).
Won't it also be better to launch this into an ASG. We have two similar instances already. Let the ASG choose where to place them instead of manually selecting subnet groups

Also, more outputs are needed to make this more configurable. I added instance_ids as an ouput in my config.

**Pull request closed without merging**
