### PR TITLE
Fix key vault creation in Azure allowing the terraform run to upload certs

### PR DESCRIPTION
**Pull request by bnferguson**
Includes https://github.com/hashicorp/private-terraform-enterprise/pull/22. 

Ran into the same problem @ausfestivus did with the key vault setup in the bootstrap. 

Luckily they wrote up their issues over in https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/issues/47 and in turn https://github.com/ausfestivus/tfe-demo/blob/master/azureKeyvaultTroubleshooting.md. The latter leading me to this branch, which solved my issues. 

Of particular interest is the user creation being done in a way that it can be done in a single pass instead of requiring two `plan` and `apply` passes (mine was still broken  after that even but this these changes patched it up) described in this issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1569#issuecomment-456035861 

Hopefully @ausfestivus doesn't mind me opening a PR for their branch. :D (and thank you for such a great set of write ups!)

### CODE REVIEW

**Review by erindatkinson — APPROVED** [review]
This looks great! Thanks to both of you!

LGTM 🌈

**Comment by bnferguson** [comment]
oh and thanks to @lhaig for getting this started in #22! 🎉

**Comment by ausfestivus** [comment]
You're welcome @bnferguson. 
I think I spent about 4 or 5 hours walking the issues here and elsewhere to get to the underlying root causes and most feasible fix considering dependant and upstream issues. Hence the detailed write ups for the next poor sod that tried to wrap their brain around it.

**Comment by lhaig** [comment]
I am very glad that my small contribution helped in some way. 
I could not dedicate as much time as I wanted, and it looks like things have moved on quite a bit. Thank you everyone.

**Pull request merged**
